project:
  type: book

execute:
  freeze: auto

book:
  page-navigation: true
  title: "Template"
  site-url: "https://dst-hdm.github.io/dst-docs/" # replace ORGNAME and REPONAME
  repo-url: https://github.com/dst-hdm/dst-docs # replace ORGNAME and REPONAME
  repo-actions: [edit, issue]
  open-graph: true
  image: "/images/logo.png"
  favicon: "/images/logo.png"
  search:
    type: overlay
  chapters:
    - Ideenfindung.qmd
    - DataPrep.qmd
    - Dashboard.qmd
    - Storyline.qmd
    - Presentation.qmd
    - index.md

format:
  html:
    toc: true
    theme:
      light: [cosmo, style/style.scss]
      dark: [cosmo, style/dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap

bibliography: references.bib
