# Entwicklung der Präsentation

## Brainstorming für den Leitfaden
Wir haben uns entschieden, unseren Leitfaden für die Präsentation am Storytelling-Ansatz von Satz Nussbaum zu orientieren. Hierbei haben wir uns intensiv mit seinen Thesen auseinandergesetzt und überlegt, wie wir diese in unsere Präsentation integrieren können. Ein entscheidender Schwerpunkt lag dabei auf der Identifizierung des Zielgruppenkontexts. Für uns war klar, dass die Präsentation vor allem für Politiker und Personen aus der Wirtschaft und Industrie konzipiert ist. Da diese Zielgruppe unterschiedliche Kenntnisse zu den Themen Temperaturanstieg und Naturkatastrophen aufweisen kann, war es unser erster Schritt, alle Teilnehmer auf den gleichen Wissensstand zu bringen. Die erste Folie sollte demnach diese Grundlagen darstellen.

Nachdem wir diese Grundidee festgelegt hatten und beide mit der weiteren Verfolgung einverstanden waren, überlegten wir uns drei Möglichkeiten zur weiteren Gestaltung der Präsentation.

### Möglichkeit 1 
Spezialisierung auf ein Land, das stark von Naturkatastrophen betroffen ist, wie zum Beispiel Indien. Hierbei hätten wir anhand von Indien die Anzahl und den Verlauf der Naturkatastrophen dargestellt. Diese Idee wurde verworfen aufgrund unserer begrenzten Datenlage und der Tatsache, dass nur ein kleiner Teil unserer Zielgruppe davon betroffen wäre.

### Möglichkeit 2
Vertiefung auf eine bestimmte Katastrophenart, wie beispielsweise Stürme. Auch hier stellte sich das Problem, dass die Zielgruppe, die von dieser Katastrophenart betroffen ist, sehr klein wäre.

### Möglichekit 3
Beleuchtung von mehreren Katastrophenarten und mehreren Ländern. Nachdem die Ideen 1 und 2 verworfen wurden, erschien uns die dritte Möglichkeit als Kompromiss. Dies ermöglichte es uns, einen Großteil unserer Hörerschaft anzusprechen, und zudem war die Datenlage zu unserem Vorteil.

## Ausarbeitung des Leitfaden 
Nachdem das Grundkonzept feststand, widmeten wir uns der Auswahl der Diagramme und der Strukturierung der Präsentation. Eine grundlegende Anforderung war es, dass die gewählten Diagramme die Storyline mit ihren Inhalten unterstützen sollten. Zusätzlich wollten wir durch ein konkretes Beispiel unserer Storyline die nötige Tiefe verleihen. Hier wählten wir bewusst den Hurrikan Katrina, da dieser eine der ersten Naturkatastrophen war, welcher uns medial so bekannt war. Hinzu liegt dieser weniger als 20 Jahre zurück, was  nochmal unsere Aussage unterstütze. 
